language: node_js
node_js:
  - "0.10"
  - "0.11"

matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"

install:
  # There's a bug that keeps node-gyp from building binaries
  # that are sub-dependencies of packages in package.json.
  # This is a temporary fix to install those packages correctly.
  - scripts/install_dependencies.sh
  - npm install --ignore-scripts
